### ISSUE TITLE
FTP datadumps locations are not supported.

### ISSUE THREAD

**Issue by JervenBolleman** [LODLaundry/llWashingMachine#2]
e.g. the uniprot datasets are marked as invalid because the somewhere a FTP uri is changed into a HTTP uri.

**Comment by wouterbeek** [comment]
Now that FTP URIs can be entered via the Website it makes sense to be able to process them as well. Unfortunately, this is not yet the case. I have opened a separate issue for this over at https://github.com/LODLaundry/lodlaundry.github.io/issues/83
