### ISSUE TITLE
Do you have any stats on the vocabularies you're finding in this data?

### ISSUE THREAD

**Issue by danbri** [LODLaundry/llWashingMachine#3]

**Comment by LaurensRietveld** [comment]
Hi @danbri , 
What kind of stats are you talking about? How often a vocab is used in certain datasets?
We don't have such stats atm. It's on our to-do list to increase findability, and create an index of used vocabularies and their corresponding datasets. Is that something you're looking for?

gr Laurens

**Comment by danbri** [comment]
I'm not particularly after anything, except that the more info that can be pooled on practical SemWeb vocab usage the better.

I did make some experiments a while back on showing visually 3 different measures. Per domain, per doc, and per triple counts. 

Hopefully http://danbri.org/words/2012/03/08/776 works for you.

Spreadsheet is here: https://docs.google.com/spreadsheet/ccc?key=0AprPQXwcGXxgdElUWHpLMUJHQTNleUZfdEdITGRrdHc&usp=sharing

**Comment by wouterbeek** [comment]
Hi @danbri ,

Statistics about LOD data are indeed very interesting! We do not see that as part of the LOD Laundromat core, but as an application that can be build on top of LOD Laundromat.

For instance [LOD-Observatory](https://github.com/wouterbeek/LOD-Observatory) is a very limited effort of mine to create an overview of all the documents in the Laundromat. Laurens has done a similar thing for a specific publication [LODAnalysis](https://github.com/LODLaundry/LODAnalysis), focusing on VoID and other metadata descriptions.

In our experience, such (statistics) applications are only be implemented from within an academic setting if they can be tied to publication opportunities. If you have ideas on such a thing then we are actually quite keen to collaborate!

Cheers,
Wouter.
